version: '3'
services:
  nginx:
    platform: linux/amd64
    image: nginx:1.23.2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./infra/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./infra/nginx/certbot/www:/var/www/certbot:ro
      - ./infra/nginx/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./infra/nginx/certbot/www:/var/www/certbot:rw
      - ./infra/nginx/certbot/conf/:/etc/letsencrypt/:rw
