---
# - include_vars: ../../vars.yml
#   name: include vars

- name: "Check directory"
  stat:
    path: "~/{{ PROJECT_FOLDER }}/{{ NGINX_CONF_FOLDER }}"
  register: my_folder

- name: "echo if directory already existed"
  debug:
    msg: "the jboss directory is already existed"
  when: my_folder.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: "~/{{ PROJECT_FOLDER }}/{{ NGINX_CONF_FOLDER }}"
    state: directory
    mode: 0755
    group: "{{ VM_USER }}"
    owner: "{{ VM_USER }}"
  when: my_folder.stat.exists == false

- name: "Copy Nginx conf file"
  ansible.builtin.copy:
    src: "{{ NGINX_CONF_NAME }}"
    dest: "~/{{ PROJECT_FOLDER }}/{{ NGINX_CONF_FOLDER }}/"
    force: true

- name: "Copy Docker Compose file"
  ansible.builtin.copy:
    src: "{{ COMPOSE_FILE_NAME }}"
    dest: "~/{{ PROJECT_FOLDER }}"
    force: true

- name: "Reatart containers"
  shell:
    cmd: "docker compose stop && docker compose rm -f && docker compose pull && docker compose up -d"
    chdir: "~/{{ PROJECT_FOLDER }}"

- name: "Request certs"
  shell:
    cmd: "docker compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ -m {{ LETSENCRYPT_EMAIL }} --agree-tos -d {{ APP_DOMAIN_NAME }}"
    chdir: "~/{{ PROJECT_FOLDER }}"

